name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 新功能'
    labels:
      - '新功能'
  - title: '🐛 Bug 修复'
    labels:
      - 'bug'
  - title: '🧰 日常维护'
    label: '日常维护'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
# 这里填写更新内容
template: |
  测试版 0.2.4
  1、由于学校教务系统官网https协议失效，特更换为http协议，请立即更新，否则影响使用
  2、新增慧生活798喝水，使用时需要先在原慧生活798绑定支付宝小额免签才可以使用
  3、修复全校课表当前节次高亮错误问题
  4、修复课程显示横屏报错问题
  5、慧生活798增加扫码收藏设备
  $CHANGES
no-changes-template: |
  快下载体验~