name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 新功能'
    labels:
      - '新功能'
  - title: '🐛 Bug 修复'
    labels:
      - 'bug'
  - title: '🧰 日常维护'
    label: '日常维护'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
# 这里填写更新内容
template: |
  测试版 v0.1.8
  修复ios语言异常问题
  新增主题页面设置
  更改macos默认图标
  修复android gradle构建报错问题
  修复schedule页面日期文本行高问题
  添加列表动画
  person新增学期和开始日期的选择
  修复安装签名

  $CHANGES
no-changes-template: |
  快下载体验~