name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 新功能'
    labels:
      - '新功能'
  - title: '🐛 Bug 修复'
    labels:
      - 'bug'
  - title: '🧰 日常维护'
    label: '日常维护'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
# 这里填写更新内容
template: |
  测试版 0.2.6
  1、新增考试查询页面
  2、新增教师课表查询页面
  $CHANGES
no-changes-template: |
  快下载体验~