display_name: Schedule
package_name: schedule

maintainer:
  name: YiQiu
  email: binzixiang@163.com

priority: optional
section: x11
installed_size: 24400

dependencies:
  - mpv
  - libappindicator3-1 | libayatana-appindicator3-1
  - gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1
  - libsecret-1-0
  - libnotify-bin
  - libjsoncpp25
  - libmpv1 | libmpv2
  - xdg-user-dirs

essential: false
icon: assets/images/logo.png

keywords:
  - Schedule

generic_name: Schedule Application
categories:
  - Schedule